### ISSUE TITLE
erro while mining

### ISSUE THREAD

**Issue by makertronic** [f04ever/noso-2m#20] opened 2023-04-11 18:43 UTC
<img width="721" alt="image" src="https://user-images.githubusercontent.com/85033212/231259044-5ce8072c-1045-4375-92c1-e0794b29d7d5.png">

any clue ? maybe password support ?

**Comment by f04ever** [comment] 2023-04-11 19:01
Hi!
This kind of issue is definitely caused by the poor connection between miner machine and pools. In general, either your internet is disconnected, or pools are offline, or firewall, ... 
You can make a `ping` to those pools to check if you can reach pools nor not?
For example, run below commands in the linux's terminal, or windows's command:

`ping pool.nosomn.com`
`ping nosofish.xyz`
`ping nosopool.estripa.online`
`ping 47.87.181.190 # propool`

Not relating to password feature.
Best!

**Comment by f04ever** [comment] 2023-04-11 19:31
A case you can check that you are using the right config file `noso-2m.cfg`.
If you are using on a PC (windows/linux/macos), `noso-2m.cfg` should contain these lines (for pool setting) :

`pools noso-mn:pool.nosomn.com:8082`
`pools fishing:nosofish.xyz:8082`
`pools estripa:nosopool.estripa.online:8082`
`pools propool:47.87.181.190:8082`

In case you are on mobile phone (android), use the IPv4 addresses for corresponding above domains
Hope that help!

**Comment by makertronic** [comment] 2023-04-11 21:48
<img width="737" alt="image" src="https://user-images.githubusercontent.com/85033212/231295352-57b03d41-f9f1-4fee-aef5-cc14e3ed067e.png">
Thanks for the answers
i dont think it's a network related issue

**Comment by f04ever** [comment] 2023-04-12 07:31
Hi! Looks nothing like cases I guessed.

Make sense with you screenshot. It shown already communicating with pools (for get blk#, hash, diff) but cannot sent shares.

That would be very nice to see this issue that rarely happens. I let `noso-2m` runs mining from year to year :-).

Can you build yourself from source code?
It would help debugging more the issue. I guess it relates to the setting of socket timeout, that is fixed in a relative short time currently. In that case, you can increase the timeout `DEFAULT_POOL_INET_TIMEOSEC` (from 60 to 600 for example) in file `config.hpp` to see the result.

You can also provide debug option in the command for more information of the issuess: `./noso-2m --logging=debug`

Best!

**Comment by makertronic** [comment] 2023-04-12 15:11
<img width="759" alt="image" src="https://user-images.githubusercontent.com/85033212/231501533-b943368e-f319-4c2a-ba06-c61db2ae8c34.png">
i'm using c++2a for standard, c++20 is not aviable. 
any clue ?

**Comment by makertronic** [comment] 2023-04-12 15:13
<img width="740" alt="image" src="https://user-images.githubusercontent.com/85033212/231502384-110f41df-12d0-4c29-8c77-e9d3091a3bdb.png">
same thing with debug enabled

**Comment by f04ever** [comment] 2023-04-22 11:34
It turned out the issue is due to pool performances recently.
With a correct config file `noso-2m.cfg`, noso-2m is still running well.
Best!

config file `noso-2m.cfg` should like below:

```
address YOURNOSOWALLETADDRESS
threads 1
pools noso-mn:47.87.138.208:8082
pools fishing:5.230.69.100:8082
pools akkarin:47.87.158.147:8082
pools estripa:20.199.50.27:8082
pools propool:47.87.181.190:8082
```

**Closed as completed** 2023-04-22 11:36 UTC
